version: '2'

services:
  elasticsearch:
    build: ./docker/elasticsearch
    volumes:
      - ./docker/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
